/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as DossiersRouteImport } from './routes/dossiers'
import { Route as IndexRouteImport } from './routes/index'

const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const DossiersRoute = DossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dossiers': typeof DossiersRoute
  '/missions': typeof MissionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dossiers': typeof DossiersRoute
  '/missions': typeof MissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dossiers': typeof DossiersRoute
  '/missions': typeof MissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dossiers' | '/missions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dossiers' | '/missions'
  id: '__root__' | '/' | '/dossiers' | '/missions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DossiersRoute: typeof DossiersRoute
  MissionsRoute: typeof MissionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossiers': {
      id: '/dossiers'
      path: '/dossiers'
      fullPath: '/dossiers'
      preLoaderRoute: typeof DossiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DossiersRoute: DossiersRoute,
  MissionsRoute: MissionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
